package io.emergeos.core.domain;

public enum AgentTraceEventType {
  MODEL_STEP,
  TOOL_REQUEST,
  TOOL_RESULT,
  TOOL_REJECTED,
  HANDOFF_REQUEST,
  HANDOFF_RESULT,
  HANDOFF_REJECTED,
  STRUCTURED_FINAL,
  ARTIFACT_COMMITTED
}
