package io.emergeos.core.domain;

public enum GraphAttemptPhase {
  MARKED,
  OPERATOR_APPROVED,
  PARENT_AUTHORIZED,
  PARENT_RUNNING,
  CHILD_AUTHORIZED,
  CHILD_RUNNING,
  EGRESS_CONSUMED,
  CREDENTIAL_READING,
  CLIENT_READY,
  MODEL_READY,
  PROVIDER_PENDING,
  PROVIDER_ATTRIBUTED,
  CHILD_TERMINAL,
  PARENT_TERMINAL,
  TERMINAL
}
