package io.emergeos.core.domain;

public enum GraphAttemptEventType {
  ATTEMPT_CLAIMED,
  OPERATOR_APPROVED,
  PARENT_AUTHORIZED,
  PARENT_STARTED,
  CHILD_AUTHORIZED,
  CHILD_STARTED,
  CHILD_EGRESS_CONSUMED,
  CREDENTIAL_READ_STARTED,
  CLIENT_CREATED,
  MODEL_CREATED,
  PROVIDER_INTENT
}
